### ISSUE TITLE
Mobile version lacks margins

### ISSUE THREAD

**Issue by AlexanderEkdahl** [belen-albeza/breathe-theme#3]
Margins on left and right side of the main body would probably improve legibility on mobile devices.

Otherwise fantastic theme - minimalist and serious.

**Comment by belen-albeza** [comment]
Thanks for reporting this. Yes, you are right. This issue will be tackled in a future release in which I'll add a responsive layout for mobile and tablets.

Cheers!

**Comment by sursh** [comment]
I am also looking forward to this. Lovely theme!

**Comment by sebinsua** [comment]
For those looking for a quick fix: set the `'max-width'` of the `.main-wrapper` to a percentage instead of `42em`.

**Comment by callmekatootie** [comment]
Any ETA on when the mobile version might come out?
